version: "3.7"

services:
  # api:
  #   image: node:14-alpine
  #   container_name: twitter-api
  #   tty: true
  #   stdin_open: true
  #   depends_on:
  #     - twitterdb
  #   ports:
  #     - ${API_PORT}:${API_PORT}
  #   working_dir: /api
  #   volumes:
  #     - ./:/api
  #     - ./.env:/api/.env
  #   # command: [ "-c", "yarn && yarn build && yarn start" ]
  #   # entrypoint: sh
  #   networks:
  #     database:
  #       ipv4_address: 10.1.1.11
  twitterdb:
    image: postgres:alpine
    container_name: twitter-db
    environment:
      POSTGRES_DB: ${DB_DATABASE}
      POSTGRES_PASSWORD: ${DB_PASSWORD}
      POSTGRES_USER: ${DB_USER}
    volumes:
      - postgres:/var/lib/postresql/data
    ports:
      - ${DB_PORT}:${DB_PORT}
    networks:
      database:
        ipv4_address: 10.1.1.10
networks:
  database:
    ipam:
      driver: default
      config:
        - subnet: "10.1.1.0/24"

volumes:
  postgres:
